"""users table

Revision ID: 77bdb7baa624
Revises: 
Create Date: 2022-01-21 17:35:31.556065

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '77bdb7baa624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    table = sa.table('user',
                     sa.Column('id', sa.Integer()),
                     sa.Column('username', sa.String(length=64)),
                     sa.Column('password_hash', sa.String(length=128)),
                     sa.Column('is_superuser', sa.Boolean()))
    op.bulk_insert(table,
                   [
                       {'username': 'admin',
                        'password_hash': 'pbkdf2:sha256:260000$JbuQVuvEh67KDtHd$33d765bdb6152c75a4ec3f89d52638ea88dccf7c03ae652d4fa15d3baf5bc1fc',
                        'is_superuser': True
                        }
                   ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
